### ISSUE TITLE
image issue - unauthorized

### ISSUE THREAD

**Issue by 3gbCyber** [misje/opencti-wazuh-connector#38]
Hello,

After I followed to document and added to docker-compose.yml it shows me this error with the image

![image](https://github.com/misje/opencti-wazuh-connector/assets/57197804/ce6f23d8-2c9a-4dc8-b3d5-5dffec15e82a)

✘ connector-wazuh Error Head "https://ghcr.io/v2/misje/opencti-connector-wazuh/manifests/0.1.0": unauthorized                                                                                           1.0s
Error response from daemon: Head "https://ghcr.io/v2/misje/opencti-connector-wazuh/manifests/0.1.0": unauthorized

How can I fix the issue?

here's my config

```

  connector-wazuh:
    image: ghcr.io/misje/opencti-connector-wazuh:0.1.0
    restart: always
    environment:
      # A timezone is needed for datetime tools to work as expected:
      - TZ=UTC
      - USE_TZ=true
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx # Replace with a token from the user you created
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Replace this with a unique ID
      - CONNECTOR_NAME=Wazuh
      - CONNECTOR_SCOPE=Artifact,Directory,Domain-Name,Email-Addr,Hostname,IPv4-Addr,IPv6-Addr,Mac-Addr,Network-Traffic,Process,Software,StixFile,Url,User-Account,User-Agent,Windows-Registry-Key,Windows-Re>
      - CONNECTOR_AUTO=true
      - CONNECTOR_LOG_LEVEL=warning
      - CONNECTOR_EXPOSE_METRICS=true
      - WAZUH_APP_URL=https://wazuh
      - WAZUH_OPENSEARCH_PASSWORD=xxxxxxxxxx # Remember double-$ if password contains $:
      - WAZUH_OPENSEARCH_URL=https://wazuh:9200
      - WAZUH_OPENSEARCH_USERNAME=cti_connector
      - WAZUH_OPENSEARCH_VERIFY_TLS=true
      - WAZUH_TLPS=TLP:AMBER+STRICT
    volumes:
      - /var/cache/wazuh
    links:
      - opencti:opencti
    depends_on:
      - opencti

```
